# permissions for end users to view loadbalancerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: loadbalancerconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: paperlb
    app.kubernetes.io/part-of: paperlb
    app.kubernetes.io/managed-by: kustomize
  name: loadbalancerconfig-viewer-role
rules:
- apiGroups:
  - lb.paperlb.com
  resources:
  - loadbalancerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.paperlb.com
  resources:
  - loadbalancerconfigs/status
  verbs:
  - get
