apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-pod-info-api
  name: k8s-pod-info-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: k8s-pod-info-api
  template:
    metadata:
      labels:
        app: k8s-pod-info-api
    spec:
      containers:
      - image: quay.io/didil/k8s-pod-info-api:21b1240
        name: k8s-pod-info-api
        env: 
        - name: "PORT"
          value: "4000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 3000
      
