apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
  annotations:
    lb.paperlb.com/load-balancer-ip: "127.0.0.1"
spec:
  ports:
  - nodePort: 30921
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
