apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-pod-info-api
  name: k8s-pod-info-api-service
  annotations:
    lb.paperlb.com/http-updater-url: "http://192.168.64.1:3000/api/v1/lb"
    lb.paperlb.com/load-balancer-host: "192.168.64.1"
    lb.paperlb.com/load-balancer-port: "8100"
    lb.paperlb.com/load-balancer-protocol: "TCP"
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 4000
  selector:
    app: k8s-pod-info-api
  type: LoadBalancer